# Build stage
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app

# Copy project files
COPY pom.xml .
COPY src ./src
# Copy .mvn settings
COPY .mvn ./ .mvn
COPY /.m2 /.m2
COPY /.m2 /root/.m2

# Make sure Maven uses settings.xml and local repo
RUN mvn clean package -s .mvn/settings.xml

# Runtime stage
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy built jar
COPY --from=builder /app/target/my-maven-app-1.0.0-jar-with-dependencies.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
