# Use the official NGINX image as the base image
FROM nginx:latest as base

# Set the environment to production
ENV NODE_ENV production
# Define the working directory
RUN pwd
# Use root user for initial setup
USER root

# Expose port 80 to allow incoming traffic
EXPOSE 80

# Stage 1: Build distribution
FROM base AS dist
COPY . .
RUN ls -al

# List files to debug
RUN echo "TESTING IN STAGE 1"

# Stage 2: Install dependencies
FROM base AS dependencies
RUN ls -al
# Copy only necessary files for installing dependencies
COPY --from=dist /app/test.txt ./test.txt
RUN ls -al
RUN ls -al /kaniko/1/app

# Start NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]
