# Use the official NGINX image as the base image
FROM nginx:latest

# Expose port 80 to allow incoming traffic
EXPOSE 80
WORKDIR /app
COPY /app/test.txt ./app/test.txt

# Start NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]
