# Use the official NGINX image as the base image
FROM nginx:latest as base

# Set the environment to production
ENV NODE_ENV production
# Define the working directory
WORKDIR /app
# Use root user for initial setup
USER root

# Expose port 80 to allow incoming traffic
EXPOSE 80

# List files to debug
RUN echo "TESTING BEFORE STAGE 1"
RUN ls -la /app

# Stage 1: Build distribution
FROM base AS dist
WORKDIR /app
COPY . ./app

# List files to debug
RUN echo "TESTING IN STAGE 1"
RUN ls -la /app

# Stage 2: Install dependencies
FROM base AS dependencies
WORKDIR /app

RUN echo "TESTING IN STAGE 2"
RUN ls -la /app

# Copy only necessary files for installing dependencies
COPY --from=dist /app/test.txt ./test.txt

# List files to debug
RUN ls -la /app

# Start NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]
